### PR TITLE
Use nicer license badge

### PR DESCRIPTION
**Pull request by jaredsburrows**
Example:
[License](http://www.apache.org/licenses/LICENSE-2.0)

### CODE REVIEW

**Comment by hal9002** [comment]
Can one of the admins review this PR?

**Comment by jaredsburrows** [comment]
@hal9002 Yes.

**Review by tasomaniac — APPROVED** [review]

**Comment by mr-archano** [comment]
@hal9002 retest this please

**Review by mr-archano — APPROVED** [review]
Thanks @jaredsburrows for the contribution!

**Comment by jaredsburrows** [comment]
@mr-archano Does @hal9002 take commands via comments?

**Comment by mr-archano** [comment]
yes @jaredsburrows, some simple ones like re-triggering a build (as I posted above) :)
not sure it does more than that tbh, I would need to check 😅

**Comment by jaredsburrows** [comment]
Ha! That is awesome!

**Pull request merged**
