### PR TITLE
Migrate to lazy tasks

### LINKED ISSUE #143: Support task configuration avoidance
This plugin configures all its tasks by default. By using the new lazy tasks APIs from Gradle 4.9+, we could make users' configuration time little more effective.

### PR DESCRIPTION
**Pull request by tasomaniac**
This PR introduces lazy task configuration in a backward compatible way. Fixes #143 

**Note:** Builds on top of #144. Please merge that first.

## Considerations:

- Upgraded to Gradle 4.10.3 (the latest 4.x) Can as well migrate to 5.x but it seems like it is not strictly necessary
- Introduced `TaskCompat` to have backward compatible lazy task configuration.
  - Before Gradle 4.9, it works just like before. 
  - In Gradle 4.9+, the new api will be used and none of the tasks will be configured.
  - Thanks to the prev work introducing TaskFactories, this was pretty easy. 🎉 

| without command plugin |
| -- | 
| Screen Shot 2019-04-06 at 11 27 53 PM |

| before | after | 
|--|--|
| Screen Shot 2019-04-06 at 11 27 25 PM | Screen Shot 2019-04-06 at 11 27 39 PM |

### CODE REVIEW

**Comment by hal9002** [comment]
Can one of the admins review this PR?

**Comment by tasomaniac** [comment]
No problem. Merge merge merge 😊😊

**Comment by tasomaniac** [comment]
So, since I needed the other changes this PR includes also #144. I couldn't open against that since I don't have write access. Since you reviewed this already, you can merge it and we can close #144

**Comment by mr-archano** [comment]
@hal9002 retest this please

**Pull request merged**
