### PR TITLE
Add Plugin ID , change from android-command to com.novoda.android-command

### PR DESCRIPTION
**Pull request by friedger**
This PR changes the plugin id from android-command to com.novoda.android-command.

This is to follow the guidelines at https://docs.gradle.org/current/userguide/custom_plugins.html#N16E5C

When this is merged a new version should be release ASAP.

### CODE REVIEW

**Comment by devisnik** [comment]
:+1:

**Comment by devisnik** [comment]
@friedger Why would we need to release ASAP after merging?

**Comment by friedger** [comment]
The readme says that you should use the new id, so we should make sure that it is available.

**Comment by devisnik** [comment]
Ah, okay.

**Comment by friedger** [comment]
Superseded by #77

**Comment by friedger** [comment]
as #77 has been reverted by #81 this adds the namespaced id

**Comment by hal9002** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://ci.novoda.com/job/gradle-android-command-plugin-prb/10/
Test PASSed.

**Comment by devisnik** [comment]
:+1:

**Pull request merged**
