### PR TITLE
80/Use bintray-release plugin

### PR DESCRIPTION
**Pull request by friedger**
This PR reverts #77, in particular 71600102b236d25ca01bb5f8035ca5ed6d91f108

This is to get back to previous release flow via CI server.

### CODE REVIEW

**Comment by hal9002** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://ci.novoda.com/job/gradle-android-command-plugin-prb/2/
Test FAILed.

**Comment by friedger** [comment]
prb is not configured correctly

**Comment by ouchadam** [comment]
It's missing the refspec, will add

**Comment by ouchadam** [comment]
ok to test

**Comment by hal9002** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://ci.novoda.com/job/gradle-android-command-plugin-prb/3/
Test PASSed.

**Comment by stefanhoth** [comment]
Thanks @ouchadam. Now I remember that this was part of the setup. Hopefully
I will as well when the next project will get this treatment from me. ;-)
On Jun 26, 2015 6:03 PM, "hal9002" <notifications@github.com> wrote:

Refer to this link for build results (access rights to CI server needed):
https://ci.novoda.com/job/gradle-android-command-plugin-prb/3/
Test PASSed.

—
Reply to this email directly or view it on GitHub
<https://github.com/novoda/gradle-android-command-plugin/pull/81#issuecomment-115741837>
.

-- 
Disclaimer: The information in this e-mail and any attachments is the 
property of Novoda Ltd and is confidential and may be legally privileged. 
This e-mail is intended solely for the person or organisation to which it 
is addressed. Any disclosure, copying or other use of the information by 
any person or organisation who is not the intended recipient is strictly 
prohibited and may be unlawful. If you have received this e-mail in error, 
please inform the sender immediately and delete/destroy this e-mail and any 
copies of it. Novoda Ltd has taken reasonable precautions to minimise the 
risk of any software viruses which may damage your systems, but we advise 
that you take the necessary steps to ensure that no virus contamination is 
suffered. Novoda Ltd does not accept any liability for any loss or damage 
caused by the transmission of any virus.

Novoda Ltd, Company No: 347444, Registered in Scotland Registered 
Office: C/O Alexander Sloan, 38 Cadogan Street, Glasgow, G2 7HF, Scotland.  VAT 
Registration Number  GB 984 2525 93

**Comment by friedger** [comment]
Thanks, anybody wants to merge?
Am 26.06.2015 18:13 schrieb "Stefan Hoth" <notifications@github.com>:

> Thanks @ouchadam. Now I remember that this was part of the setup. Hopefully
> I will as well when the next project will get this treatment from me. ;-)

**Comment by devisnik** [comment]
:+1:

**Pull request merged**
