### PR TITLE
Task to enable/disable system animations. 

### PR DESCRIPTION
**Pull request by tasomaniac**
This was done a while ago. I just remembered now. 

Our `AndroidCommandPluginExtension` and `VariantConfigurator` classes are currently used to generate tasks. They create the task for each variant, in a separate group for each variant. 

SystemAnimation do not need that. 

So right now, I am creating the task manually. 

I've talked to @devisnik about it. The next step would be to refactor `AdbTask` and `VariantConfigurator` classes to make them more extensible. Also we found some statements in java style which can be refactored to groovy al the things.

### CODE REVIEW

**Comment by xrigau** [comment]
👍

**Comment by xrigau** [comment]
https://github.com/novoda/gradle-android-command-plugin/releases/tag/v1.6.1 💥

**Comment by tasomaniac** [comment]
Thanks @xrigau 
I've edited the release and added Sebastian's name as well.

**Comment by xrigau** [comment]
Oh missed that, thanks @tasomaniac !

**Pull request merged**
